parent_dir = "exp\\adult\\many-exps\\1"
real_data_path = "data/adult/"
num_numerical_features = 6
model_type = "mlp"
seed = 0
device = "cuda:0"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    128,
    128,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 10
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 50
lr = 0.0019625245852390133
weight_decay = 0.0
batch_size = 256

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[tabular_processor]
type = "bgm"

[sample]
num_samples = 2
batch_size = 10000
seed = 1

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
