parent_dir = "outputs/exp/adult-bgm/adultbgm_tuning_best"
real_data_path = "data/adult-bgm/"
num_numerical_features = 6
model_type = "mlp"
seed = 0
device = "cuda:0"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    128,
    256,
    256,
    1024,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 5000
lr = 0.0015758647906489686
weight_decay = 0.0
batch_size = 256

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 20
batch_size = 10000
seed = 0
disbalance = "__none__"

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
